### ISSUE TITLE
DEBUG is set to True in Production

### ISSUE THREAD

**Issue by ace-n** [grokit/website_grokit_ca#2]
The [Django documentation](https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/#debug) says this is a bad idea. (It's [also a security risk](https://security.stackexchange.com/questions/46171/is-it-a-good-practice-to-show-403-unauthorized-access-error-to-user), since attackers can see errors in plain sight and may have an easier time breaking into the website.)

Screenshot:
<img width="928" alt="screen shot 2016-01-31 at 3 09 36 pm" src="https://cloud.githubusercontent.com/assets/2309317/12704986/b0e60b7c-c82c-11e5-9cb1-9067c38a6c7f.png">

**Comment by grokit** [comment]
Fixed with check-in 71f542a1d6d589c4250935f06a7f89c262b43ac8.
